import:
  - ~/.config/alacritty/themes/themes/nord.yaml

window:
  option_as_alt: OnlyLeft

key_bindings:
  - { key: Left, mods: Alt, chars: "\x1bb" } # Skip word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # Skip word right
  - { key: Left, mods: Command, chars: "\x1bOH", mode: AppCursor } # Home
  - { key: Right, mods: Command, chars: "\x1bOF", mode: AppCursor } # End
  - { key: Back, mods: Command, chars: "\x15" } # Delete line
  - { key: Back, mods: Alt, chars: "\x1b\x7f" } # Delete word
  - { key: T, mods: Command, action: SpawnNewInstance }
  - { key: Space, mods: Alt, chars: " " }

font:
  normal:
    family: ComicCode Nerd Font
  size: 11
  offset:
    x: 1
    y: 7
  glyph_offset:
    x: 0
    y: 3

debug:
  print_events: true
